incorrect-syntax: "&cSintaxis incorrecta! Usa: &f/passchange (contraseña antigua) (Contraseña nueva)"
contraseña-cambiada: "&aHas cambiado tu contraseña."
contraseña-erronea: "&cContraseña incorrecta!"